apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: demoproject
  labels:
    project: robotShop
    application: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: robotShop
      application: cart
  template:
    metadata:
      namespace: demoproject
      labels:
        project: robotShop
        application: cart
    spec:
      containers:
        - name: cart
          image: cart:1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
            - name: INSTANA_AGENT_HOST
              value: host
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Always

