apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: demoproject
  labels:
    project: robotShop
    application: cart
spec:
  selector:
    project: robotShop
    application: cart
  ports:
    - name: cart-port
      protocol: TCP
      port: 8080
      targetPort: 8080