apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql
  namespace: psql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250m
  volumeName: psql
